export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const GET_PREMIUM_RESTAURANT_REQUEST = "GET_PREMIUM_RESTAURANT_REQUEST";
export const GET_GIFT_CARD_REQUEST = "GET_GIFT_CARD_REQUEST";
export const GET_HEALTH_REQUEST = "GET_HEALTH_REQUEST";